import { useEffect, useState } from "react";
import type { ApiClient, Catalog, PlanetChoice, PlannerContext, PlannerResult, RecipeReport, Target, TemplateResult } from "./piPlannerTypes";
import { dependencyIds } from "./piPlannerState";
import { CommoditySelect, downloadPi, PiNumberField, piNumber as n, plannerPath } from "./PiPlannerControls";

const cutName = (cut: number) => cut < 0 ? "Extract P0" : `Buy through P${cut}`;
export function PiPlanResults({result, catalog, selected, onSelect, onTemplate}: {result: PlannerResult; catalog: Catalog; selected: number; onSelect: (i: number) => void; onTemplate: (i: number) => void}) {
  const plan = result.plans[selected];
  const e = plan?.economics;
  const targetName = (targets: Record<string, number>) => Object.entries(targets).map(([id, quantity]) => `${catalog[id]?.name ?? id} × ${n(quantity)}`).join(" + ");
  const errors = Object.entries(result.market.errors);
  const stale = Object.values(result.market.books).some(b => new Date(b.expires_at).getTime() <= Date.now());
  return <section className="pi-results">
    <div className="pi-toolbar"><div><h3>Best plans found</h3><p>{result.search.evaluated} candidates · {n(result.search.seconds)} seconds · {result.search.cancelled ? "cancelled" : result.search.timed_out ? "time budget reached" : "search complete"}</p></div><small>ESI {result.market.hub} · {new Date(result.market.fetched_at).toLocaleString()}{result.replayed_snapshot ? " · replayed snapshot" : ""}</small></div>
    {stale && <p className="pi-notice">One or more ESI price snapshots have expired. Fetch prices again before acting on this plan.</p>}
    {errors.length > 0 && <details className="pi-card"><summary>{errors.length} commodities have unavailable ESI prices</summary>{errors.map(([id, message]) => <p key={id}>{catalog[id]?.name ?? id}: {message}</p>)}</details>}
    {!result.plans.length && <p className="mini-alert">No feasible proposal found for the requested quotas and constraints. Review the reasons below.</p>}
    <div className="table-wrap"><table><caption>Alternative production and sourcing plans</caption><thead><tr><th>Product / weekly output</th><th>Source</th><th>Colonies</th><th>Operating ISK / week</th><th>After setup amortization</th><th>Setup ISK</th><th>Select</th></tr></thead><tbody>{result.plans.map((p, i) => <tr key={i} className={selected === i ? "pi-selected" : ""}><td>{p.idle ? "Build nothing additional" : targetName(p.targets)}</td><td>{p.idle ? "Keep current" : cutName(p.sourcing_cut)}</td><td>{p.colonies.length}</td><td>{n(p.economics.operating_net)}</td><td>{n(p.economics.net_after_setup_amortization)}</td><td>{n(p.economics.setup)}</td><td><button type="button" aria-pressed={i === selected} onClick={() => onSelect(i)}>View</button></td></tr>)}</tbody></table></div>
    {plan?.idle && <p className="pi-notice">{plan.reason}. The search found no positive incremental return after the configured costs and setup amortization.</p>}
    {plan && !plan.idle && e && <>
      <div className="pi-metrics"><article><span>Operating ISK / week</span><strong>{n(e.operating_net)}</strong><small>{e.patient_estimate ? "Patient sale estimate" : "Visible bid depth only"}</small></article><article><span>ISK / visit</span><strong>{n(e.isk_per_visit)}</strong><small>{n(e.isk_per_active_hour)} ISK / active hour</small></article><article><span>Setup payback</span><strong>{e.payback_weeks == null ? "No positive payback" : `${n(e.payback_weeks)} weeks`}</strong><small>First-week cash: {n(e.first_week_cash)} ISK</small></article><article><span>Haul per week</span><strong>{n(e.haul_m3)} m³</strong><small>{n(e.trips_per_visit)} trips per visit</small></article></div>
      <div className="pi-ledger pi-card"><h4>Weekly cost ledger</h4><dl>{([["revenue", "Sales revenue"], ["inputs", "Purchased inputs"], ["customs", "Customs · all import/export legs"], ["sales_tax", "Sales tax"], ["broker_fees", "Broker fees"], ["freight", "Freight"], ["overhead", "Overhead"], ["net_after_setup_amortization", "Net after setup amortization"]] as const).map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{n(e[key])} ISK</dd></div>)}</dl></div>
      {!!e.unfilled_sale_units && <p className="pi-notice">{n(e.unfilled_sale_units)} output units have no confirmed immediate sale. {e.patient_estimate ? "Patient-sale revenue assumes later fills." : "These units contribute zero revenue."}</p>}
      <div className="pi-colony-grid">{plan.colonies.map((colony, i) => <article className="pi-card" key={i}><h4>{colony.character_name} · {colony.planet.name}</h4><p>{colony.replaces_colony_id ? "Proposed replacement" : "Proposed new colony"} · {catalog[colony.product_type_id]?.name} · {n(Object.values(colony.outputs).reduce((a,b) => a+b, 0))}/week</p><div className="pi-capacity"><span>CPU {n(colony.cpu)} / {n(colony.cpu_limit)}</span><meter min={0} max={colony.cpu_limit} value={colony.cpu} /><span>Power {n(colony.power)} / {n(colony.power_limit)}</span><meter min={0} max={colony.power_limit} value={colony.power} /><span>Visit buffer {n(colony.storage_required_m3)} / {n(colony.storage_m3)} m³</span><meter min={0} max={colony.storage_m3} value={colony.storage_required_m3} /></div><ul>{colony.facilities.map((f, j) => <li key={j}>{f.count} × {f.name}{f.heads ? ` · ${f.heads} heads` : ""}</li>)}</ul><small>Factory utilization {n(colony.weekly_factory_utilization * 100)}% · customs {n(colony.customs_isk)} ISK/week</small><button type="button" onClick={() => onTemplate(i)}>Preview native template</button></article>)}</div>
      <div className="table-wrap"><table><caption>ESI purchases and sales for this proposal</caption><thead><tr><th>Item</th><th>Action</th><th>Requested</th><th>Filled by snapshot</th><th>Unfilled</th><th>ISK</th></tr></thead><tbody>{[...plan.shopping.map(q => ({...q, action: "Buy"})), ...plan.sales.map(q => ({...q, action: e.patient_estimate ? "Patient sell" : "Sell"}))].map((q, i) => <tr key={i}><td>{catalog[q.type_id]?.name ?? q.type_id}</td><td>{q.action}</td><td>{n(q.quantity)}</td><td>{n(q.filled)}</td><td>{n(q.unfilled)}</td><td>{n(q.value)}</td></tr>)}</tbody></table></div>
      <details className="pi-card"><summary>Visit schedule & surplus</summary><p>{plan.schedule.visits_per_week} visits/week, every {n(plan.schedule.interval_hours)} hours; extraction duty cycle {n(plan.schedule.extraction_uptime_fraction * 100)}%.</p><ol>{plan.schedule.actions.map(a => <li key={a}>{a}</li>)}</ol><ul>{Object.entries(plan.surplus).filter(([,q]) => q > 0).map(([id,q]) => <li key={id}>{catalog[id]?.name}: {n(q)} unused batch surplus</li>)}</ul></details>
      {plan.notes.length > 0 && <ul className="pi-note">{plan.notes.map(note => <li key={note}>{note}</li>)}</ul>}
    </>}
    <details className="pi-card"><summary>Constraints, provenance & search limits</summary><p>{result.search.method}</p><p>Allocation engine: {result.engine.used}. {result.engine.fallback_reason}</p>{result.search.unexamined_type_ids.length > 0 && <p className="mini-alert">Time ran out before examining: {result.search.unexamined_type_ids.map(id => catalog[id]?.name ?? id).join(", ")}. Narrow the product selection or increase the search budget.</p>}<ul>{result.assumptions.map(a => <li key={a}>{a}</li>)}</ul><p>{result.baseline.note}</p><small>Input fingerprint: {result.input_sha256}</small></details>
    {result.failures.length > 0 && <details className="pi-card"><summary>Why other candidates did not fit ({result.failures.length} examples)</summary><ul>{result.failures.map((f,i) => <li key={i}>{targetName(f.targets)} · {cutName(f.cut)}: {f.reason}</li>)}</ul></details>}
  </section>;
}

function Chain({catalog, targets}: {catalog: Catalog; targets: number[]}) {
  const ids = dependencyIds(catalog, targets);
  const [focus, setFocus] = useState<number | null>(null);
  const layers = [0,1,2,3,4].map(t => ids.filter(id => catalog[id].tier === t));
  const height = Math.max(180, ...layers.map(l => l.length * 70 + 50));
  const position = (id: number) => ({x: catalog[id].tier * 215 + 15, y: layers[catalog[id].tier].indexOf(id) * 70 + 35});
  return <div className="pi-chain"><h4>Production chain</h4><div className="pi-chain-scroll"><svg viewBox={`0 0 1100 ${height}`} role="img" aria-label="PI recipe dependency graph"><defs><marker id="pi-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0 L10 5 L0 10z" fill="currentColor" /></marker></defs>{ids.flatMap(id => catalog[id].recipe?.inputs.map(input => {const a=position(input.type_id), b=position(id); return <path key={`${id}-${input.type_id}`} d={`M${a.x+180} ${a.y+22} C${a.x+205} ${a.y+22}, ${b.x-25} ${b.y+22}, ${b.x} ${b.y+22}`} markerEnd="url(#pi-arrow)" fill="none" stroke="currentColor" opacity={.5} />;}) ?? [])}{ids.map(id => {const p=position(id);return <g key={id} transform={`translate(${p.x},${p.y})`}><rect width="180" height="44" rx="7" className={focus===id ? "pi-node selected" : "pi-node"} /><text x="9" y="18">{catalog[id].name.length > 25 ? catalog[id].name.slice(0,24)+"…" : catalog[id].name}</text><text x="9" y="34" className="pi-node-tier">P{catalog[id].tier}{catalog[id].recipe ? ` · ${catalog[id].recipe!.output.quantity} per batch` : " · extraction"}</text></g>;})}</svg></div><label>Inspect chain item<select value={focus ?? ""} onChange={e => setFocus(e.target.value ? Number(e.target.value) : null)}><option value="">Select an item</option>{ids.map(id => <option key={id} value={id}>{catalog[id].name}</option>)}</select></label>{focus && catalog[focus] && <p>{catalog[focus].recipe ? `${catalog[focus].recipe!.inputs.map(i => `${i.quantity} ${i.name}`).join(" + ")} → ${catalog[focus].recipe!.output.quantity} ${catalog[focus].name}; ${n(catalog[focus].recipe!.cycle_time/60)} minutes per batch.` : `Found on: ${catalog[focus].planet_types.join(", ")}.`} Volume {catalog[focus].volume?.toLocaleString(undefined, {maximumFractionDigits: 6}) ?? "—"} m³/unit.</p>}</div>;
}

export function PiRecipeTools({api, context, targets, buyTypeIds}: {api: ApiClient; context: PlannerContext; targets: Target[]; buyTypeIds: number[]}) {
  const [localTargets, setTargets] = useState(targets);
  const [inventory, setInventory] = useState<Target[]>([]);
  const [report, setReport] = useState<RecipeReport | null>(null);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [calculated, setCalculated] = useState("");
  const {catalog} = context;
  const inputKey = JSON.stringify([localTargets, inventory, buyTypeIds]);
  async function calculate() {
    setBusy(true);setError("");
    try {setReport(await api<RecipeReport>(`${plannerPath}/recipe`, {method:"POST", body: JSON.stringify({targets:localTargets, inventory, buy_type_ids:buyTypeIds})}));setCalculated(inputKey);} catch(e) {setError(e instanceof Error ? e.message : "Recipe calculation failed");} finally {setBusy(false);}
  }
  const totals = (values: Record<string, number>) => Object.entries(values).filter(([,q])=>q>0).map(([id,q]) => <tr key={id}><td>{catalog[id]?.name ?? id}</td><td>{n(q)}</td><td>{n(q*(catalog[id]?.volume ?? 0))}</td></tr>);
  return <section className="pi-card"><h3>Recipe & inventory calculator</h3><p>Whole batches, shared ingredients, and stock you already own. This is a one-off material calculation; operation profits use recurring purchased inputs.</p>
    <form onSubmit={e=>{e.preventDefault();void calculate();}}>{localTargets.map((t,i)=><div className="pi-inline" key={i}><CommoditySelect label={`Target ${i+1}`} catalog={catalog} value={t.type_id} filter={id=>!!catalog[id].recipe} onChange={id=>setTargets(localTargets.map((r,j)=>j===i?{...r,type_id:id}:r))}/><PiNumberField label="Required units" value={t.quantity} min={1} onChange={q=>setTargets(localTargets.map((r,j)=>j===i?{...r,quantity:q}:r))}/></div>)}
    <h4>Available inventory</h4><div className="button-row compact"><button type="button" onClick={()=>setInventory(Object.entries(context.baseline.observed_inventory).map(([id,q])=>({type_id:Number(id),quantity:q})))}>Use last observed colony inventory</button><button type="button" disabled={inventory.length>=200} onClick={()=>setInventory([...inventory,{type_id:Number(Object.keys(catalog)[0]),quantity:0}])}>Add item</button><button type="button" onClick={()=>setInventory([])}>Clear inventory</button></div>
    {inventory.map((t,i)=><div className="pi-inline" key={i}><CommoditySelect catalog={catalog} value={t.type_id} onChange={id=>setInventory(inventory.map((r,j)=>j===i?{...r,type_id:id}:r))}/><PiNumberField label="Owned units" value={t.quantity} onChange={q=>setInventory(inventory.map((r,j)=>j===i?{...r,quantity:q}:r))}/><button type="button" onClick={()=>setInventory(inventory.filter((_,j)=>i!==j))}>Remove</button></div>)}<p className="pi-note">Observed stock may be old or spread across planets. Check availability before allocating it.</p><button type="submit" disabled={busy || !localTargets.length}>Calculate batches & shopping</button></form>
    {error&&<p role="alert" className="mini-alert">{error}</p>}<Chain catalog={catalog} targets={localTargets.map(t=>t.type_id)} />
    {report&&<>{calculated!==inputKey&&<p className="pi-notice">Inputs changed. Calculate again to update the material list.</p>}<div className="table-wrap"><table><caption>Missing materials to purchase or extract</caption><thead><tr><th>Commodity</th><th>Units</th><th>m³</th></tr></thead><tbody>{totals(report.shopping)}</tbody></table></div><div className="table-wrap"><table><caption>Production batches</caption><thead><tr><th>Product</th><th>Batches</th><th>Output</th><th>Surplus</th></tr></thead><tbody>{Object.values(report.nodes).map(r=><tr key={r.type_id}><td>{catalog[r.type_id]?.name}</td><td>{n(r.batches)}</td><td>{n(r.quantity)}</td><td>{n(r.quantity-r.required)}</td></tr>)}</tbody></table></div><details><summary>Other products buildable directly from this stock</summary><p>{report.buildable_note}</p><ul>{report.buildable_direct.map(t=><li key={t.type_id}>{catalog[t.type_id]?.name}: {n(t.quantity)}</li>)}</ul></details><button type="button" onClick={()=>downloadPi("eqm-pi-materials.json",report)}>Export materials</button></>}
  </section>;
}

type ScoutResult = {systems: {system_id:number;name:string;security?:number;score:number;planets:(PlanetChoice&{resource_type_ids:number[]})[];covered_resources?:number[];missing_resources?:number[];error?:string}[]; note:string; as_of:string};
export function PiScout({api,catalog,rawIds,onAdd}: {api:ApiClient;catalog:Catalog;rawIds:number[];onAdd:(p:PlanetChoice[])=>void}) {
  const [regions,setRegions]=useState<{id:number;name:string}[]>([]);
  const [region,setRegion]=useState("");
  const [systems,setSystems]=useState<{id:number;name:string;security:number}[]>([]);
  const [chosen,setChosen]=useState<number[]>([]);
  const [result,setResult]=useState<ScoutResult|null>(null);
  const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{void api<{id:number;name:string}[]>(`${plannerPath}/regions`).then(setRegions).catch(e=>setError(e.message));},[]);
  useEffect(()=>{if(!region)return;const abort=new AbortController();setChosen([]);setSystems([]);void api<typeof systems>(`${plannerPath}/systems?region_id=${region}`,{signal:abort.signal}).then(setSystems).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[region]);
  async function scout(){setBusy(true);setError("");try{setResult(await api<ScoutResult>(`${plannerPath}/scout`,{method:"POST",body:JSON.stringify({system_ids:chosen,resource_type_ids:rawIds})}));}catch(e){setError(e instanceof Error?e.message:"Scouting failed");}finally{setBusy(false);}}
  return <section className="pi-card"><h3>Scout planets</h3><p>Compare systems by the planet types needed for your selected production chain. Density and customs rates must be checked in-game.</p><div className="pi-fields"><label>Region<select aria-label="Region" value={region} onChange={e=>setRegion(e.target.value)}><option value="">Select region</option>{regions.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Systems · choose up to 25<select multiple size={10} value={chosen.map(String)} onChange={e=>setChosen(Array.from(e.target.selectedOptions).slice(0,25).map(o=>Number(o.value)))}>{systems.map(s=><option value={s.id} key={s.id}>{s.name} · {n(s.security)}</option>)}</select></label></div><p>Needed raw resources: {rawIds.map(id=>catalog[id]?.name).join(", ")||"all planet types"}</p><button type="button" disabled={busy||!chosen.length} onClick={()=>void scout()}>{busy?"Reading ESI universe data…":"Compare selected systems"}</button>{error&&<p className="mini-alert" role="alert">{error}</p>}{result&&<><p className="pi-note">{result.note}</p>{result.systems.map(s=><details className="pi-planet" key={s.system_id}><summary>{s.name} · {s.planets.length} planets · {s.score} matches{s.error?` · ${s.error}`:""}</summary>{s.missing_resources?.length? <p>Missing: {s.missing_resources.map(id=>catalog[id]?.name).join(", ")}</p>:null}<button type="button" onClick={()=>onAdd(s.planets.map(({resource_type_ids:_,...p})=>p))}>Add these planets to scenario</button><ul>{s.planets.map(p=><li key={p.key}>{p.name} · {p.planet_type} · {n(p.diameter_km)} km diameter<button type="button" onClick={()=>{const {resource_type_ids:_,...candidate}=p;onAdd([candidate]);}}>Add planet</button></li>)}</ul></details>)}</>}
  </section>;
}

export function PiTemplateTools({api,value,onChange,catalog}: {api:ApiClient;value:TemplateResult|null;onChange:(v:TemplateResult)=>void;catalog:Catalog}) {
  const [text,setText]=useState(value?JSON.stringify(value.template,null,2):"");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [copied,setCopied]=useState(false);
  useEffect(()=>{if(value)setText(JSON.stringify(value.template,null,2));},[value]);
  const points=value?.template.P.map(p=>({x:p.Lo,y:p.La}))??[];
  const minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minY=Math.min(...points.map(p=>p.y)),maxY=Math.max(...points.map(p=>p.y));
  const point=(index:number)=>{const p=points[index];return{x:40+(p.x-minX)/Math.max(.0001,maxX-minX)*720,y:40+(p.y-minY)/Math.max(.0001,maxY-minY)*340};};
  async function inspect(){setBusy(true);setError("");try{onChange(await api<TemplateResult>(`${plannerPath}/templates/inspect`,{method:"POST",body:JSON.stringify({text})}));}catch(e){setError(e instanceof Error?e.message:"Template validation failed");}finally{setBusy(false);}}
  return <section className="pi-card"><h3>Native template workbench</h3><p>Generate an original layout from a proposed colony, or inspect your own exported EVE clipboard JSON.</p><label>Template JSON<textarea rows={8} maxLength={250000} value={text} onChange={e=>{setText(e.target.value);setCopied(false);}} placeholder="Paste an EVE planetary template here" /></label><button type="button" disabled={busy||!text} onClick={()=>void inspect()}>Validate & preview</button>{error&&<p role="alert" className="mini-alert">{error}</p>}{value&&<><p className="pi-notice">{value.validation}</p><p>{value.summary.planet_type} · {value.summary.facilities} facilities · {value.summary.links} links · {value.summary.routes} routes · CCU {value.template.CmdCtrLv}</p><svg className="pi-template-map" viewBox="0 0 800 420" role="img" aria-label="Projected facility and link layout">{value.template.L.map((l,i)=>{const a=point(l.S-1),b=point(l.D-1);return <line key={i} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="currentColor" opacity={.5}/>;})}{value.template.P.map((p,i)=>{const pos=point(i);return <g key={i} transform={`translate(${pos.x},${pos.y})`}><circle r="13" className="pi-node"/><text textAnchor="middle" y="4">{i+1}</text><title>{p.S?catalog[p.S]?.name:"Storage / launchpad"} · type {p.T}</title></g>;})}</svg>{value.instructions&&<ol>{value.instructions.map(s=><li key={s}>{s}</li>)}</ol>}<div className="button-row compact"><button type="button" onClick={()=>downloadPi("eqm-pi-template.json",value.template)}>Download validated template</button><button type="button" onClick={()=>void navigator.clipboard.writeText(JSON.stringify(value.template)).then(()=>setCopied(true)).catch(()=>setError("Clipboard unavailable. Download the template instead."))}>{copied?"Copied":"Copy validated template"}</button></div>{text!==JSON.stringify(value.template,null,2)&&<p className="pi-note">Exports use the last validated preview. Validate again to include your edits.</p>}</>}
  </section>;
}
