import { Archive, BadgeDollarSign, ClipboardList, Plus, RotateCcw, Save, Search, Settings2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { FittingImportResult } from "../../types/fittings";
import "../fleetOperations.css";

type ApiClient = <T>(path: string, options?: RequestInit) => Promise<T>;
type Choice = { id: number; name: string; ship_name?: string | null; character_name?: string | null; is_draft?: boolean };
type PriorityOption = { id?: number; label: string; value: string; short_code?: string | null; display_order: number; is_active: boolean };
type PriorityField = { id: number; key: string; name: string; field_type: "select" | "text" | "number" | "boolean"; is_required: boolean; display_order: number; is_active: boolean; options: PriorityOption[] };
type DoctrineFit = { link_id: number; fitting_id: number; fitting_name: string; ship_name?: string | null; is_primary: boolean; sort_order: number };
type DoctrinePlan = { link_id: number; skill_plan_id: number; skill_plan_name: string; fitting_id?: number | null; fitting_name?: string | null; ship_name?: string | null; sort_order: number };
type Doctrine = { id: number; name: string; purpose?: string | null; notes?: string | null; priority_code?: string | null; priority_values: Record<string, string | number | boolean>; priority_code_manual: boolean; fitting_id?: number | null; fitting_name?: string | null; ship_name?: string | null; fittings: DoctrineFit[]; fitting_count: number; linked_skill_plan_id?: number | null; linked_skill_plan_name?: string | null; skill_plan_links: DoctrinePlan[]; is_shared: boolean; archived_at?: string | null; created_by?: string | null; created_at: string; updated_at: string };
type Meta = { can_manage: boolean; priority_fields: PriorityField[]; all_priority_fields: PriorityField[]; fittings: Choice[]; skill_plans: Choice[]; characters: Choice[] };
type DoctrineAppraisal = { doctrine_id: number; doctrine_name: string; combined: { hubs: { key: string; label: string }[]; totals: Record<string, { buy_total: number; sell_total: number; split_total: number }> }; fittings: { fitting_id: number; fitting_name: string; ship_name?: string | null; is_primary: boolean; totals: Record<string, { buy_total: number; sell_total: number; split_total: number }> }[] };

const blank = { name: "", purpose: "", fitting_ids: [] as string[], primary_fitting_id: "", priority_values: {} as Record<string, string | number | boolean>, priority_code: "", priority_code_manual: false, notes: "", skill_plan_links: [] as {skill_plan_id:string;fitting_id:string}[], is_shared: true };
const isk = new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 });

export function DoctrinePage({ api, onOpenFitting, onOpenSkillPlan }: { api: ApiClient; onOpenFitting: (name: string) => void; onOpenSkillPlan: (planId: number) => void }) {
  const [rows, setRows] = useState<Doctrine[]>([]); const [meta, setMeta] = useState<Meta | null>(null);
  const [selected, setSelected] = useState<Doctrine | null>(null); const [form, setForm] = useState({ ...blank });
  const [editing, setEditing] = useState(false); const [search, setSearch] = useState(""); const [priorityFilter, setPriorityFilter] = useState("");
  const [includeArchived, setIncludeArchived] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const [fitSearch, setFitSearch] = useState(""); const [customFitText, setCustomFitText] = useState(""); const [customCharacterId, setCustomCharacterId] = useState("");
  const [appraisal, setAppraisal] = useState<DoctrineAppraisal | null>(null); const [appraising, setAppraising] = useState(false);
  const [fieldDraft, setFieldDraft] = useState({ name: "", key: "", field_type: "select", is_required: false, options: "" });

  async function load() { const query = new URLSearchParams({ q: search, priority: priorityFilter, include_archived: String(includeArchived) }); const [nextRows, nextMeta] = await Promise.all([api<Doctrine[]>(`/doctrines?${query}`), api<Meta>("/doctrines/meta")]); setRows(nextRows); setMeta(nextMeta); }
  useEffect(() => { void load().catch((err) => setError(err instanceof Error ? err.message : "Could not load doctrines")); }, [includeArchived]);
  useEffect(() => { const timer = window.setTimeout(() => void load().catch(() => undefined), 250); return () => window.clearTimeout(timer); }, [search, priorityFilter]);
  useEffect(() => { sessionStorage.setItem("eqm-doctrine-draft", JSON.stringify(form)); }, [form]);

  function startCreate() { const saved = sessionStorage.getItem("eqm-doctrine-draft"); setSelected(null); setAppraisal(null); setForm(saved ? { ...blank, ...JSON.parse(saved), fitting_ids: JSON.parse(saved).fitting_ids ?? [] } : { ...blank }); setEditing(true); setMessage(null); }
  function startEdit(row: Doctrine) { setSelected(row); setAppraisal(null); setForm({ name: row.name, purpose: row.purpose ?? "", fitting_ids: row.fittings.map((fit) => String(fit.fitting_id)), primary_fitting_id: String(row.fitting_id ?? row.fittings[0]?.fitting_id ?? ""), priority_values: row.priority_values ?? {}, priority_code: row.priority_code ?? "", priority_code_manual: row.priority_code_manual, notes: row.notes ?? "", skill_plan_links: (row.skill_plan_links?.length ? row.skill_plan_links : row.linked_skill_plan_id ? [{skill_plan_id:row.linked_skill_plan_id,fitting_id:row.fitting_id}] : []).map((link)=>({skill_plan_id:String(link.skill_plan_id),fitting_id:String(link.fitting_id??"")})), is_shared: row.is_shared }); setEditing(true); }
  const filteredFits = useMemo(() => (meta?.fittings ?? []).filter((fit) => `${fit.name} ${fit.ship_name ?? ""} ${fit.character_name ?? ""}`.toLowerCase().includes(fitSearch.toLowerCase())).slice(0, 100), [meta, fitSearch]);

  async function save() { setBusy(true); setError(null); try { const payload = { ...form, purpose: form.purpose.trim() || null, fitting_ids: form.fitting_ids.map(Number), primary_fitting_id: form.primary_fitting_id ? Number(form.primary_fitting_id) : null, skill_plan_links: form.skill_plan_links.map((link)=>({skill_plan_id:Number(link.skill_plan_id),fitting_id:link.fitting_id?Number(link.fitting_id):null})) }; const row = await api<Doctrine>(selected ? `/doctrines/${selected.id}` : "/doctrines", { method: selected ? "PATCH" : "POST", body: JSON.stringify(payload) }); setSelected(row); setEditing(false); sessionStorage.removeItem("eqm-doctrine-draft"); setMessage(`Doctrine ${selected ? "updated" : "created"}.`); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Could not save doctrine"); } finally { setBusy(false); } }
  async function importFit() { if (!customCharacterId || !customFitText.trim()) return; setBusy(true); setError(null); try { const result = await api<FittingImportResult>("/fittings/import-text", { method: "POST", body: JSON.stringify({ character_id: Number(customCharacterId), text: customFitText }) }); if (form.is_shared) await api(`/fittings/${result.fitting.id}`, { method: "PATCH", body: JSON.stringify({ is_shared: true }) }); await load(); setForm((current) => ({ ...current, fitting_ids: [...current.fitting_ids, String(result.fitting.id)], primary_fitting_id: current.primary_fitting_id || String(result.fitting.id) })); setFitSearch(result.fitting.name); setCustomFitText(""); setMessage(`Created and added ${result.fitting.name} in Fittings.${form.is_shared ? " The fit was shared for doctrine access." : ""}${result.warnings.length ? ` ${result.warnings.join(" ")}` : ""}`); } catch (err) { setError(err instanceof Error ? err.message : "Could not import fit"); } finally { setBusy(false); } }
  async function appraise(row: Doctrine) { setAppraising(true); setError(null); try { setAppraisal(await api<DoctrineAppraisal>(`/doctrines/${row.id}/appraise`, { method: "POST", body: JSON.stringify({ hubs: ["jita", "amarr", "hek", "dodixie", "rens"] }) })); } catch (err) { setError(err instanceof Error ? err.message : "Could not appraise doctrine"); } finally { setAppraising(false); } }
  async function archive(row: Doctrine) { if (!window.confirm(`${row.archived_at ? "Restore" : "Archive"} ${row.name}? Historical links will be preserved.`)) return; await api(row.archived_at ? `/doctrines/${row.id}/restore` : `/doctrines/${row.id}`, { method: row.archived_at ? "POST" : "DELETE", body: row.archived_at ? "{}" : undefined }); setSelected(null); await load(); }
  async function addPriorityField() { const key = (fieldDraft.key || fieldDraft.name).toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, ""); const options = fieldDraft.field_type === "select" ? fieldDraft.options.split(",").map((raw, index) => { const [label, code] = raw.trim().split("|"); return { label, value: label.toLowerCase().replace(/[^a-z0-9]+/g, "_"), short_code: code?.trim() || null, display_order: index, is_active: true }; }).filter((row) => row.label) : []; await api("/doctrines/priority-fields", { method: "POST", body: JSON.stringify({ key, name: fieldDraft.name, field_type: fieldDraft.field_type, is_required: fieldDraft.is_required, display_order: (meta?.priority_fields.length ?? 0) * 10, is_active: true, options }) }); setFieldDraft({ name: "", key: "", field_type: "select", is_required: false, options: "" }); await load(); }
  async function togglePriorityField(field: PriorityField) { await api(`/doctrines/priority-fields/${field.id}`, { method: "PUT", body: JSON.stringify({ ...field, is_active: !field.is_active, options: field.options.map(({ id: _id, ...option }) => option) }) }); await load(); }

  return <section className="fleet-ops-page">
    <section className="panel stacked"><div className="section-heading"><div><h3>Doctrine Management</h3><p className="muted">Multi-fit doctrines, configurable priority, market appraisal, and readiness plans in one operational record.</p></div>{meta?.can_manage && <button onClick={startCreate}><Plus size={17}/> New doctrine</button>}</div>
      {message && <div className="notice inline">{message}</div>}{error && <div className="mini-alert">{error}</div>}
      <div className="fleet-filter-grid"><label>Search<div className="input-with-icon"><Search size={16}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Name, purpose, or notes"/></div></label><label>Priority<input value={priorityFilter} onChange={(event) => setPriorityFilter(event.target.value)} placeholder="Priority code"/></label><label className="check"><input type="checkbox" checked={includeArchived} onChange={(event) => setIncludeArchived(event.target.checked)}/> Include archived</label></div>
      <div className="fleet-split"><div className="card-list fleet-record-list">{rows.map((row) => <article key={row.id} className={selected?.id === row.id ? "selected" : ""}><button className="fleet-record-button" onClick={() => { setSelected(row); setEditing(false); }}><span className="badge-row"><b>{row.priority_code || "LEGACY"}</b>{row.archived_at && <small>Archived</small>}</span><strong>{row.name}</strong><span>{row.ship_name || "No fit linked"} · {row.purpose || "Legacy event doctrine"}</span></button></article>)}{rows.length === 0 && <p className="empty">No doctrines match these filters.</p>}</div>
        <div className="fleet-detail">{editing ? renderDoctrineForm() : selected ? renderDoctrineDetail(selected) : <p className="empty">Choose a doctrine or create one.</p>}</div></div>
    </section>
    {meta?.can_manage && <details className="panel fleet-config"><summary><Settings2 size={17}/> Priority field configuration</summary><div className="stacked"><div className="card-list">{meta.all_priority_fields.map((field) => <article key={field.id}><strong>{field.name} <code>{field.key}</code></strong><span>{field.is_active ? "active" : "inactive"} · {field.field_type} · {field.is_required ? "required" : "optional"} · {field.options.map((option) => `${option.label}${option.short_code ? ` (${option.short_code})` : ""}`).join(", ") || "free entry"}</span><button onClick={() => void togglePriorityField(field)}>{field.is_active ? "Deactivate" : "Activate"}</button></article>)}</div><div className="form-grid"><label>Name<input value={fieldDraft.name} onChange={(e) => setFieldDraft({...fieldDraft,name:e.target.value})}/></label><label>Key<input value={fieldDraft.key} onChange={(e) => setFieldDraft({...fieldDraft,key:e.target.value})} placeholder="auto-generated"/></label><label>Type<select value={fieldDraft.field_type} onChange={(e) => setFieldDraft({...fieldDraft,field_type:e.target.value})}><option value="select">Select</option><option value="text">Text</option><option value="number">Number</option><option value="boolean">Boolean</option></select></label></div>{fieldDraft.field_type === "select" && <label>Allowed values <span className="muted">Comma-separated; add <code>Label|CODE</code> for a short code.</span><input value={fieldDraft.options} onChange={(e) => setFieldDraft({...fieldDraft,options:e.target.value})} placeholder="Strategic|S, Standard|N"/></label>}<label className="check"><input type="checkbox" checked={fieldDraft.is_required} onChange={(e) => setFieldDraft({...fieldDraft,is_required:e.target.checked})}/> Required</label><div className="button-row"><button disabled={!fieldDraft.name.trim()} onClick={() => void addPriorityField()}>Add field</button></div></div></details>}
  </section>;

  function renderDoctrineDetail(row: Doctrine) { const hubs = appraisal?.combined.hubs ?? []; const plans=row.skill_plan_links??[]; return <article className="fleet-detail-card"><div className="section-heading"><div><span className="fleet-code">{row.priority_code || "LEGACY"}</span><h3>{row.name}</h3></div>{meta?.can_manage && <div className="button-row compact"><button onClick={() => startEdit(row)}>Edit</button><button className="danger" onClick={() => void archive(row)}>{row.archived_at ? <RotateCcw size={16}/> : <Archive size={16}/>} {row.archived_at ? "Restore" : "Archive"}</button></div>}</div><p>{row.purpose || "No purpose has been added yet."}</p><dl className="fleet-definition-list"><div><dt>Fittings ({row.fitting_count})</dt><dd><div className="card-list">{row.fittings.map((fit) => <button key={fit.link_id} type="button" className="text-button" onClick={() => onOpenFitting(fit.fitting_name)}>{fit.fitting_name} · {fit.ship_name}{fit.is_primary ? " · PRIMARY" : ""}</button>)}{row.fittings.length === 0 && "None attached"}</div></dd></div><div><dt>Skill plans ({plans.length})</dt><dd><div className="card-list">{plans.map((plan)=><button key={plan.link_id} className="text-button" onClick={()=>onOpenSkillPlan(plan.skill_plan_id)}>{plan.skill_plan_name}{plan.fitting_name?` · ${plan.fitting_name}`:" · doctrine-wide"}</button>)}{!plans.length&&"None"}</div></dd></div><div><dt>Priority values</dt><dd>{Object.entries(row.priority_values ?? {}).map(([key,value]) => `${key}: ${String(value)}`).join(" · ") || "None configured"}</dd></div><div><dt>Audit</dt><dd>Created by {row.created_by || "unknown"} on {new Date(row.created_at).toLocaleString()} · updated {new Date(row.updated_at).toLocaleString()}</dd></div></dl>{row.notes && <div className="fleet-notes">{row.notes}</div>}<div className="button-row"><button type="button" disabled={appraising || row.fittings.length === 0} onClick={() => void appraise(row)}><BadgeDollarSign size={16}/> {appraising ? "Appraising" : appraisal?.doctrine_id === row.id ? "Refresh appraisal" : "Market appraisal"}</button></div>{appraisal?.doctrine_id === row.id && <div className="stacked"><h4>Market appraisal</h4>{hubs.map((hub) => { const total = appraisal.combined.totals[hub.key]; return total ? <article key={hub.key}><strong>{hub.label}</strong><span>Buy {isk.format(total.buy_total)} ISK · Split {isk.format(total.split_total)} ISK · Replace {isk.format(total.sell_total)} ISK</span></article> : null; })}<h4>Per fitting</h4>{appraisal.fittings.map((fit) => <article key={fit.fitting_id}><strong>{fit.fitting_name} · {fit.ship_name}{fit.is_primary ? " · primary" : ""}</strong><span>{hubs.map((hub) => `${hub.label}: ${isk.format(fit.totals[hub.key]?.sell_total ?? 0)} ISK replacement`).join(" · ")}</span></article>)}</div>}</article>; }
  function renderDoctrineForm() { function toggleFit(id: string) { setForm((current) => { const attached = current.fitting_ids.includes(id); const fitting_ids = attached ? current.fitting_ids.filter((value) => value !== id) : [...current.fitting_ids, id]; return { ...current, fitting_ids, primary_fitting_id: current.primary_fitting_id === id ? (fitting_ids[0] ?? "") : (current.primary_fitting_id || id) }; }); } return <form className="stacked-form" onSubmit={(e) => { e.preventDefault(); void save(); }}><div className="section-heading"><h3>{selected ? "Edit doctrine" : "New doctrine"}</h3><button type="button" onClick={() => setEditing(false)}>Cancel</button></div><label>Name<input required value={form.name} onChange={(e) => setForm({...form,name:e.target.value})}/></label><label>Purpose <span className="muted">optional</span><input maxLength={500} value={form.purpose} onChange={(e) => setForm({...form,purpose:e.target.value})}/></label><label>Search fittings<div className="input-with-icon"><Search size={16}/><input value={fitSearch} onChange={(e) => setFitSearch(e.target.value)} placeholder="Fit, ship, or character"/></div></label><div className="stacked"><strong>Attached fittings ({form.fitting_ids.length})</strong><span className="muted">Add as many fits as the doctrine needs. The primary fit remains the default in older linked workflows.</span><div className="card-list">{filteredFits.map((fit) => <label key={fit.id} className="check"><input type="checkbox" checked={form.fitting_ids.includes(String(fit.id))} onChange={() => toggleFit(String(fit.id))}/><span>{fit.name} · {fit.ship_name}{fit.is_draft ? " · draft" : ""}</span></label>)}</div></div>{form.fitting_ids.length > 0 && <label>Primary fit<select value={form.primary_fitting_id} onChange={(e) => setForm({...form,primary_fitting_id:e.target.value})}>{form.fitting_ids.map((id) => { const fit = meta?.fittings.find((item) => item.id === Number(id)); return <option key={id} value={id}>{fit?.name ?? `Fit ${id}`} · {fit?.ship_name}</option>; })}</select></label>}{form.primary_fitting_id && <button type="button" className="secondary-action" onClick={() => onOpenFitting(meta?.fittings.find((fit) => fit.id === Number(form.primary_fitting_id))?.name ?? "")}><ClipboardList size={16}/> Inspect primary fit</button>}
      <details className="inline-creator"><summary>Create a custom fit without leaving this form</summary><label>Owning character<select value={customCharacterId} onChange={(e) => setCustomCharacterId(e.target.value)}><option value="">Choose your character</option>{meta?.characters.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>EFT text<textarea rows={8} value={customFitText} onChange={(e) => setCustomFitText(e.target.value)} placeholder="[Ship, Fit name]…"/></label><button type="button" disabled={busy || !customCharacterId || !customFitText.trim()} onClick={() => void importFit()}><Plus size={16}/> Save into Fittings and select</button></details>
      {(meta?.priority_fields ?? []).map((field) => <label key={field.id}>{field.name}{field.is_required ? " *" : ""}{field.field_type === "select" ? <select required={field.is_required} value={String(form.priority_values[field.key] ?? "")} onChange={(e) => setForm({...form,priority_values:{...form.priority_values,[field.key]:e.target.value}})}><option value="">Not set</option>{field.options.filter((row) => row.is_active).map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : field.field_type === "boolean" ? <select required={field.is_required} value={String(form.priority_values[field.key] ?? "")} onChange={(e) => setForm({...form,priority_values:{...form.priority_values,[field.key]:e.target.value === "true"}})}><option value="">Not set</option><option value="true">Yes</option><option value="false">No</option></select> : <input required={field.is_required} type={field.field_type === "number" ? "number" : "text"} value={String(form.priority_values[field.key] ?? "")} onChange={(e) => setForm({...form,priority_values:{...form.priority_values,[field.key]:field.field_type === "number" ? Number(e.target.value) : e.target.value}})}/>}</label>)}
      <label className="check"><input type="checkbox" checked={form.priority_code_manual} onChange={(e) => setForm({...form,priority_code_manual:e.target.checked})}/> Enter final priority code manually</label>{form.priority_code_manual && <label>Priority code<input required value={form.priority_code} onChange={(e) => setForm({...form,priority_code:e.target.value})}/></label>}<div className="stacked"><div className="section-heading compact"><div><strong>Linked skill plans ({form.skill_plan_links.length})</strong><p className="muted">Attach a core plan to each ship, or leave its fitting blank for doctrine-wide requirements.</p></div><button type="button" onClick={()=>setForm({...form,skill_plan_links:[...form.skill_plan_links,{skill_plan_id:"",fitting_id:""}]})}><Plus size={16}/> Add plan</button></div>{form.skill_plan_links.map((link,index)=><div key={index} className="form-grid"><label>Skill plan<select required value={link.skill_plan_id} onChange={(e)=>{const next=[...form.skill_plan_links];next[index]={...link,skill_plan_id:e.target.value};setForm({...form,skill_plan_links:next});}}><option value="">Choose plan</option>{meta?.skill_plans.filter((plan)=>plan.id===Number(link.skill_plan_id)||!form.skill_plan_links.some((current)=>current.skill_plan_id===String(plan.id))).map((row)=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Applies to<select value={link.fitting_id} onChange={(e)=>{const next=[...form.skill_plan_links];next[index]={...link,fitting_id:e.target.value};setForm({...form,skill_plan_links:next});}}><option value="">Entire doctrine</option>{form.fitting_ids.map((id)=>{const fit=meta?.fittings.find((item)=>item.id===Number(id));return <option key={id} value={id}>{fit?.name??`Fit ${id}`} · {fit?.ship_name}</option>;})}</select></label><button type="button" className="danger" onClick={()=>setForm({...form,skill_plan_links:form.skill_plan_links.filter((_,itemIndex)=>itemIndex!==index)})}>Remove</button></div>)}</div><label>Notes<textarea value={form.notes} onChange={(e) => setForm({...form,notes:e.target.value})} placeholder="Operational context, restrictions, and guidance"/></label><label className="check"><input type="checkbox" checked={form.is_shared} onChange={(e) => setForm({...form,is_shared:e.target.checked})}/> Shared doctrine</label><button type="submit" disabled={busy}><Save size={17}/> {busy ? "Saving" : "Save doctrine"}</button></form>; }
}
