import { Archive, ArrowDown, ArrowUp, Copy, Download, Merge, Plus, Save, Sparkles, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import "../fleetOperations.css";

type ApiClient = <T>(path: string, options?: RequestInit) => Promise<T>;
type Entry = { id?: number; skill_type_id: number; skill_name: string; target_level: number; sort_order: number; notes?: string | null; introduced_by: string[]; trained_level?: number; state?: string };
type Plan = { id: number; name: string; description?: string | null; notes?: string | null; source: string; character_id?: number | null; character_name?: string | null; fitting_id?: number | null; fitting_name?: string | null; source_doctrine_id?: number | null; source_doctrine_name?: string | null; can_manage: boolean; progress: {complete:number;partial:number;missing:number;total:number}; entries: Entry[] };
type Meta = { characters: {id:number;name:string}[]; fittings:{id:number;name:string;ship_name?:string|null}[]; doctrines:{id:number;name:string;fitting_id:number}[] };
type Preview = { fitting_id:number; fitting_name:string; doctrine_id?:number|null; entries:Entry[]; data_source:string; complete:boolean; warnings:string[] };

export function SkillPlansPanel({ api, selectedPlanId }: { api: ApiClient; selectedPlanId?: number | null }) {
  const [plans,setPlans]=useState<Plan[]>([]); const [meta,setMeta]=useState<Meta|null>(null); const [selected,setSelected]=useState<Plan|null>(null);
  const [editing,setEditing]=useState(false); const [form,setForm]=useState({name:"",description:"",notes:"",character_id:"",fitting_id:"",source_doctrine_id:"",source:"manual",entries:[] as Entry[]});
  const [generateFrom,setGenerateFrom]=useState<"fitting"|"doctrine">("fitting"); const [generateId,setGenerateId]=useState(""); const [skillSearch,setSkillSearch]=useState(""); const [skillChoices,setSkillChoices]=useState<{type_id:number;name:string}[]>([]);
  const [message,setMessage]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  const [mergeIds,setMergeIds]=useState<string[]>([]);
  async function load(){const [rows,metadata]=await Promise.all([api<Plan[]>("/skill-plans"),api<Meta>("/skill-plans/meta")]);setPlans(rows);setMeta(metadata);}
  useEffect(()=>{void load().catch((e)=>setError(e instanceof Error?e.message:"Could not load skill plans"));},[]);
  useEffect(()=>{if(!selectedPlanId)return;const local=plans.find((plan)=>plan.id===selectedPlanId);if(local){setSelected(local);setEditing(false);return;}void api<Plan>(`/skill-plans/${selectedPlanId}`).then((plan)=>{setSelected(plan);setEditing(false);}).catch((e)=>setError(e instanceof Error?e.message:"Could not open skill plan"));},[selectedPlanId,plans]);
  useEffect(()=>{if(!skillSearch.trim()){setSkillChoices([]);return;}const timer=window.setTimeout(()=>void api<{type_id:number;name:string}[]>(`/skill-plans/search/skills?q=${encodeURIComponent(skillSearch)}`).then(setSkillChoices).catch(()=>undefined),250);return()=>clearTimeout(timer);},[skillSearch]);
  function startBlank(){setSelected(null);setForm({name:"",description:"",notes:"",character_id:"",fitting_id:"",source_doctrine_id:"",source:"manual",entries:[]});setEditing(true);}
  function edit(row:Plan){setSelected(row);setForm({name:row.name,description:row.description??"",notes:row.notes??"",character_id:String(row.character_id??""),fitting_id:String(row.fitting_id??""),source_doctrine_id:String(row.source_doctrine_id??""),source:row.source,entries:row.entries.map((entry)=>({...entry}))});setEditing(true);}
  async function generate(){if(!generateId)return;setBusy(true);setError(null);try{const preview=await api<Preview>("/skill-plans/generate-preview",{method:"POST",body:JSON.stringify(generateFrom==="doctrine"?{doctrine_id:Number(generateId)}:{fitting_id:Number(generateId)})});setSelected(null);setForm({name:`${preview.fitting_name} Minimum Requirements`,description:`Base requirements generated from ${preview.fitting_name}.`,notes:preview.warnings.join("\n"),character_id:"",fitting_id:String(preview.fitting_id),source_doctrine_id:String(preview.doctrine_id??""),source:preview.doctrine_id?"doctrine":"fitting",entries:preview.entries});setEditing(true);setMessage(`Generated ${preview.entries.length} deduplicated minimum requirements from ${preview.data_source}. Review before saving.`);}catch(e){setError(e instanceof Error?e.message:"Generation failed");}finally{setBusy(false);}}
  function move(index:number,delta:number){const next=[...form.entries];const target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setForm({...form,entries:next.map((row,i)=>({...row,sort_order:i}))});}
  function addSkill(choice:{type_id:number;name:string}){if(form.entries.some((row)=>row.skill_type_id===choice.type_id))return;setForm({...form,entries:[...form.entries,{skill_type_id:choice.type_id,skill_name:choice.name,target_level:1,sort_order:form.entries.length,introduced_by:["Manual addition"]}]});setSkillSearch("");setSkillChoices([]);}
  async function save(){setBusy(true);setError(null);try{const payload={...form,character_id:form.character_id?Number(form.character_id):null,fitting_id:form.fitting_id?Number(form.fitting_id):null,source_doctrine_id:form.source_doctrine_id?Number(form.source_doctrine_id):null,entries:form.entries.map(({skill_name:_name,trained_level:_trained,state:_state,id:_id,...row},index)=>({...row,sort_order:index}))};const saved=await api<Plan>(selected?`/skill-plans/${selected.id}`:"/skill-plans",{method:selected?"PUT":"POST",body:JSON.stringify(payload)});setSelected(saved);setEditing(false);setMessage("Skill plan saved.");await load();}catch(e){setError(e instanceof Error?e.message:"Could not save plan");}finally{setBusy(false);}}
  async function archive(row:Plan){if(!confirm(`Archive ${row.name}? Doctrine and fit history will remain intact.`))return;await api(`/skill-plans/${row.id}`,{method:"DELETE"});setSelected(null);await load();}
  async function copyForEve(row:Plan){try{await navigator.clipboard.writeText(eveSkillPlanText(row));setMessage(`Copied ${eveSkillPlanLineCount(row).toLocaleString()} ordered skill levels for EVE. In the EVE skill-plan content menu, choose Import Skills from Clipboard.`);setError(null);}catch(e){setError(e instanceof Error?e.message:"Could not copy the skill plan");}}
  function downloadForEve(row:Plan){const blob=new Blob([eveSkillPlanText(row)],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`${safeFilename(row.name)}-eve-skill-plan.txt`;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);setMessage(`Downloaded ${eveSkillPlanLineCount(row).toLocaleString()} ordered skill levels in EVE clipboard format.`);setError(null);}
  async function mergePlans(){if(mergeIds.length<2)return;setBusy(true);setError(null);try{const preview=await api<{name:string;source:string;entries:Entry[];source_plan_names:string[]}>("/skill-plans/merge-preview",{method:"POST",body:JSON.stringify({plan_ids:mergeIds.map(Number)})});setSelected(null);setForm({name:preview.name,description:`Master plan merged from ${preview.source_plan_names.join(", ")}.`,notes:"",character_id:"",fitting_id:"",source_doctrine_id:"",source:"merged",entries:preview.entries});setEditing(true);setMessage(`Combined ${preview.source_plan_names.length} plans into ${preview.entries.length} unique skills. Highest target levels were retained; review and save the master plan.`);}catch(e){setError(e instanceof Error?e.message:"Could not merge plans");}finally{setBusy(false);}}
  return <section className="panel stacked skill-plans-page"><div className="section-heading"><div><h3>Skill Plans</h3><p className="muted">Editable plans with fitting-derived minimum requirements and live character progress.</p></div><button onClick={startBlank}><Plus size={17}/> Blank plan</button></div>{message&&<div className="notice inline">{message}</div>}{error&&<div className="mini-alert">{error}</div>}
    <div className="generation-strip"><label>Generate from<select value={generateFrom} onChange={(e)=>{setGenerateFrom(e.target.value as "fitting"|"doctrine");setGenerateId("");}}><option value="fitting">Fitting</option><option value="doctrine">Doctrine</option></select></label><label>{generateFrom==="fitting"?"Fitting":"Doctrine"}<select value={generateId} onChange={(e)=>setGenerateId(e.target.value)}><option value="">Choose…</option>{(generateFrom==="fitting"?meta?.fittings:meta?.doctrines)?.map((row)=><option key={row.id} value={row.id}>{row.name}{"ship_name" in row&&row.ship_name?` · ${row.ship_name}`:""}</option>)}</select></label><button disabled={busy||!generateId} onClick={()=>void generate()}><Sparkles size={17}/> Generate review</button></div><details className="inline-creator"><summary><Merge size={17}/> Combine skill plans into a master plan</summary><p className="muted">Select two or more plans. Duplicate skills are merged at the highest requested level.</p><div className="card-list">{plans.map((plan)=><label key={plan.id} className="check"><input type="checkbox" checked={mergeIds.includes(String(plan.id))} onChange={(e)=>setMergeIds(e.target.checked?[...mergeIds,String(plan.id)]:mergeIds.filter((id)=>id!==String(plan.id)))}/>{plan.name}</label>)}</div><button type="button" disabled={busy||mergeIds.length<2} onClick={()=>void mergePlans()}><Merge size={17}/> Combine {mergeIds.length} plans</button></details>
    <div className="fleet-split"><div className="card-list fleet-record-list">{plans.map((row)=><article key={row.id}><button className="fleet-record-button" onClick={()=>{setSelected(row);setEditing(false);}}><span className="badge-row"><b>{row.source}</b><small>{row.progress.complete}/{row.progress.total} complete</small></span><strong>{row.name}</strong><span>{row.character_name||"No progress character"} · {row.fitting_name||"Manual plan"}</span></button></article>)}{!plans.length&&<p className="empty">No skill plans yet.</p>}</div><div className="fleet-detail">{editing?renderPlanForm():selected?renderPlanDetail(selected):<p className="empty">Choose a plan, create a blank one, or generate from a fitting.</p>}</div></div>
  </section>;
  function renderPlanDetail(row:Plan){const lineCount=eveSkillPlanLineCount(row);return <article className="fleet-detail-card"><div className="section-heading"><div><span className="fleet-code">{row.source}</span><h3>{row.name}</h3></div><div className="button-row compact"><button type="button" disabled={!row.entries.length} onClick={()=>void copyForEve(row)} title="Copy a level-by-level list for EVE's Import Skills from Clipboard action"><Copy size={16}/> Copy for EVE</button><button type="button" disabled={!row.entries.length} onClick={()=>downloadForEve(row)} title="Download the same EVE-compatible clipboard list as UTF-8 text"><Download size={16}/> Download</button>{row.can_manage&&<><button onClick={()=>edit(row)}>Edit</button><button className="danger" onClick={()=>void archive(row)}><Archive size={16}/> Archive</button></>}</div></div><p>{row.description}</p><div className="notice inline">EVE export expands each target into ordered training levels ({lineCount.toLocaleString()} lines). Paste it through Skills → Skill Plans → plan content menu → Import Skills from Clipboard.{lineCount>150?" This plan exceeds EVE's 150-skill-level personal-plan limit; split it or import sections as needed.":""}</div><div className="skill-plan-progress"><span className="scope-ok">{row.progress.complete} complete</span><span className="scope-warn">{row.progress.partial} partial</span><span className="mini-alert">{row.progress.missing} missing</span></div><div className="mini-list">{row.entries.map((entry)=><div key={entry.skill_type_id}><strong>{entry.skill_name} {toRoman(entry.target_level)}</strong><span>Trained {entry.trained_level??0} · {entry.state} · {entry.introduced_by.join("; ")||"Manual"}</span></div>)}</div></article>}
  function renderPlanForm(){return <form className="stacked-form" onSubmit={(e)=>{e.preventDefault();void save();}}><div className="section-heading"><h3>Review and edit plan</h3><button type="button" onClick={()=>setEditing(false)}>Cancel</button></div><label>Name<input required value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></label><div className="form-grid"><label>Progress character<select value={form.character_id} onChange={(e)=>setForm({...form,character_id:e.target.value})}><option value="">None</option>{meta?.characters.map((row)=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Linked fitting<select value={form.fitting_id} onChange={(e)=>setForm({...form,fitting_id:e.target.value})}><option value="">None</option>{meta?.fittings.map((row)=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Linked doctrine<select value={form.source_doctrine_id} onChange={(e)=>{const doctrine=meta?.doctrines.find((row)=>row.id===Number(e.target.value));setForm({...form,source_doctrine_id:e.target.value,fitting_id:doctrine?String(doctrine.fitting_id):form.fitting_id});}}><option value="">None</option>{meta?.doctrines.map((row)=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label></div><label>Add skill<input value={skillSearch} onChange={(e)=>setSkillSearch(e.target.value)} placeholder="Search SDE skills"/></label>{skillChoices.length>0&&<div className="skill-choice-list">{skillChoices.map((row)=><button type="button" key={row.type_id} onClick={()=>addSkill(row)}>{row.name}</button>)}</div>}<div className="skill-plan-editor">{form.entries.map((entry,index)=><div key={entry.skill_type_id}><strong>{entry.skill_name}</strong><label>Target<select value={entry.target_level} onChange={(e)=>{const entries=[...form.entries];entries[index]={...entry,target_level:Number(e.target.value)};setForm({...form,entries});}}>{[1,2,3,4,5].map((level)=><option key={level} value={level}>{toRoman(level)}</option>)}</select></label><label>Notes<input value={entry.notes??""} onChange={(e)=>{const entries=[...form.entries];entries[index]={...entry,notes:e.target.value};setForm({...form,entries});}}/></label><small>{entry.introduced_by.join("; ")}</small><div className="button-row compact"><button type="button" aria-label="Move up" onClick={()=>move(index,-1)}><ArrowUp size={15}/></button><button type="button" aria-label="Move down" onClick={()=>move(index,1)}><ArrowDown size={15}/></button><button type="button" className="danger" onClick={()=>setForm({...form,entries:form.entries.filter((_,i)=>i!==index)})}><Trash2 size={15}/></button></div></div>)}</div><label>Plan notes<textarea value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></label><button type="submit" disabled={busy}><Save size={17}/> Save reviewed plan</button></form>}
}
function toRoman(level:number){return ["","I","II","III","IV","V"][level]??String(level)}
function eveSkillPlanText(plan:Plan){return plan.entries.flatMap((entry)=>Array.from({length:entry.target_level},(_,index)=>`${entry.skill_name} ${toRoman(index+1)}`)).join("\r\n");}
function eveSkillPlanLineCount(plan:Plan){return plan.entries.reduce((total,entry)=>total+entry.target_level,0);}
function safeFilename(value:string){return value.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")||"eqm-skill-plan";}
